name: CI/CD Pipeline for Node.js Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm ci  # Faster than npm install for CI/CD

      - name: Run Tests and Save Results
        run: |
          mkdir -p test-results
          npm run check -- --json > test-results/test-results.json

      - name: Upload Test Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results

  deploy:
    name: Build and Deploy
    needs: test  # Ensures test job runs first
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: ./test-results

      - name: Display Test Results
        run: cat ./test-results/test-results.json || echo "No test results found"

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: |
          npm run build  # Ensure this script exists in package.json

      - name: Deploy Application Using PM2
        run: |
          echo "Listing files before deployment..."
          ls -a

          echo "Checking PM2 status..."
          pm2 status

          # Stop existing app if running
          pm2 delete node-app || true

          # Start new process
          pm2 start ./src/server.js --name node-app

          # Save PM2 process list
          pm2 save
