name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  # ---------------------------
  # 1) TEST JOB
  # ---------------------------
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run "npm check"
        run: |
          npm check > check-results.txt

      - name: Archive check results
        uses: actions/upload-artifact@v4
        with:
          name: check-results
          path: check-results.txt
          if-no-files-found: error

  # ---------------------------
  # 2) DEPLOY JOB
  # ---------------------------
  deploy:
    needs: [ test ]
    # Replace or add custom labels if your self-hosted runner requires them
    runs-on: self-hosted

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: check-results

      - name: Display check results
        run: cat check-results.txt

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies on self-hosted runner
        run: npm install

      - name: Run Deployment with PM2
        run: |
          # 1. Cleanup: Remove existing process if running
          pm2 delete node-app || true

          # 2. Start Application with absolute path
          pm2 start "./src/server.js" --name node-app

          # 3. Save PM2 configuration
          pm2 save

          echo "Deployment completed on self-hosted runner!"
